### ISSUE TITLE
[Bug] Mission 2 of Don Sielke's does not load completely 

### ISSUE THREAD

**Issue by DatMaxNub** [luciusDXL/TheForceEngine#182]
Version: 1.01
Game: Dark Forces
Mission: Don Sielke's Levels for Dark Forces - https://df-21.net/downloads/levels/df42/df42_modern.zip

Upon starting Level 2 of this pack. TFE fails to load the mission. However you can still press escape to get the pause menu. Pressing F1 for the PDA will crash

![Screenshot 2023-01-07 17-46-50](https://user-images.githubusercontent.com/19301383/211173151-1d46c973-c902-4a77-8a31-9a2cb00ad03b.png)

![Screenshot 2023-01-07 17-46-52](https://user-images.githubusercontent.com/19301383/211173155-2eaab355-5511-4b74-bbb5-7579ef2a96f2.png)

[crashdump.zip](https://github.com/luciusDXL/TheForceEngine/files/10367330/crashdump.zip)

**Comment by Karjala22** [comment]
I fixed it - they somehow added a space in front of the  level. 

```
 LEV 2.1
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# This file has been created by DSielke@AOL.COM, NEW BASE LEVEL
#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
LEVELNAME TALAY
PALETTE TALAY.PAL
MUSIC DEFAULT.GMD
PARALLAX 1024.0000 1024.0000

#`~`~`~`~`~`~`~`~`~`~`~`~`~`~`~`~`~`~`~`~`~`~`~`~`~`~`~`~`~`~`~`~`~`~`~`~
#               T e x t u r e   T a b l e
#
#`~`~`~`~`~`~`~`~`~`~`~`~`~`~`~`~`~`~`~`~`~`~`~`~`~`~`~`~`~`~`~`~`~`~`~`~
#   Lowercase textures are from the 'Extra' list.
```

[TALAY.zip](https://github.com/luciusDXL/TheForceEngine/files/10367337/TALAY.zip)

**Comment by TP555** [comment]
Hi

That isn't a real Temporary Fix to play it in TFE  ?
The TALAY.LEV is the same file like in the Gob , of course Paste the File in Dark Forces . Dir. didn't fix the problem  !

**Comment by luciusDXL** [comment]
This is fixed locally, and will be fixed in the version 1.02 release.

**Comment by luciusDXL** [comment]
Fixed in the version 1.02 Release.
